name: vakifbank_finance_app
description: A professional finance app for Vakıfbank
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

  # State Management
  flutter_bloc: ^9.1.1
  provider: ^6.1.5

  # Architecture
  get_it: ^8.0.3
  equatable: ^2.0.7
  dartz: ^0.10.1

  # Network
  http: ^1.4.0

  # Local Storage
  shared_preferences: ^2.5.3

  # Utilities
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1

  # Code Generation
  json_annotation: ^4.9.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/